### PR TITLE
Many cleanups, changes and improvements

### PR DESCRIPTION
**Pull request by VoltrexMaster**
1- Cleaned up the code as much as possible
2- Changed and added some missing documentations
3- Fixed a lot of errors
4- Improved properties
5- Better method implementations

### CODE REVIEW

**Comment by AndrewDaGuy** [comment]
what the *[REDACTED]* is this

**Review by Misly16 — APPROVED** [review]

**Review by AndrewDaGuy — APPROVED** [review]
seems safe indeed since ~~99.999%~~ is all double quote and grave marks to single quote and **S P A C E S**

**Review by matthewthechickenman — APPROVED** [review]
Good to me. @loggers-bro still needs to review

**Comment by Million900o** [comment]
I like these changes

**Comment by matthewthechickenman** [comment]
actually FUCK IT

**Pull request merged**
