### PR TITLE
Cleanups, documentation improvements, better implementations

### PR DESCRIPTION
**Pull request by VoltrexMaster**
Cleaned up redundant code, added new and missing and improved documentations and JSDoc and improved method implantations.

### CODE REVIEW

**Comment by matthewthechickenman** [comment]
The code's looking good to me, I'm going to test it now

**Review by Misly16 — APPROVED** [review]

**Comment by alebot-dev** [comment]
Looking good to me. I'll wait for Matt to finish testing but for now to have the all clear

**Comment by matthewthechickenman** [comment]
I've not done any testing but I'll be following this up with a little fix
The way that you said _sendMessage would return a Promise<object> broke the Message struct, I've fixed it now and I'll revert this PR and re-commit with the correct code added. The rest of the code seems to be fine tho.

**Comment by VoltrexMaster** [comment]
> I've not done any testing but I'll be following this up with a little fix
> The way that you said _sendMessage would return a Promise broke the Message struct, I've fixed it now and I'll revert this PR and re-commit with the correct code added. The rest of the code seems to be fine tho.

Wait how did it break though

**Comment by matthewthechickenman** [comment]
> > I've not done any testing but I'll be following this up with a little fix
> > The way that you said _sendMessage would return a Promise broke the Message struct, I've fixed it now and I'll revert this PR and re-commit with the correct code added. The rest of the code seems to be fine tho.
> 
> Wait how did it break though

It was saying that .id and shit wasn't part of an {}. This is why I made a structure for TS to base it off of. Minor mistake, easily fixed, and your code has been merged.

**Comment by Misly16** [comment]
@all-contributors add @VoltrexMaster for code

**Pull request merged**
