### PR TITLE
Add new collaborators

### PR DESCRIPTION
**Pull request by matthewthechickenman**

### CODE REVIEW

**Comment by Misly16** [comment]
we could use something like this to add contributors https://allcontributors.org/

**Comment by matthewthechickenman** [comment]
> we could use something like this to add contributors https://allcontributors.org/

then set it up 👁️

**Comment by alebot-dev** [comment]
this is fine

**Review by alebot-dev — APPROVED** [review]
add dat bad boi

**Comment by Misly16** [comment]
@all-contributors please add @matthewthechickenman for ideas

**Comment by alebot-dev** [comment]
@all-contributors please add @alebot-dev for code

**Comment by alebot-dev** [comment]
@all-contributors please add @Misly16 for code

**Comment by alebot-dev** [comment]
@all-contributors please add @Starman3787 for code

**Comment by Misly16** [comment]
@all-contributors add @Misly16 for code design

**Comment by Misly16** [comment]
@all-contributors add @Misly16 for code design

**Comment by Misly16** [comment]
@all-contributors add @vierofernando for docs

**Comment by Misly16** [comment]
and thats everyone

**Pull request merged**
