### PR TITLE
Cleanups, typings fixes, documentation improvements and tsc lint fixed

### PR DESCRIPTION
**Pull request by VoltrexMaster**
Cleaned up redundant code, fixed some typings, implemented better documentation and fixed all the tsc lint issues.

### CODE REVIEW

**Comment by matthewthechickenman** [comment]
hehe 69 lol

**Comment by CedarBlocks** [comment]
🤔

**Comment by VoltrexMaster** [comment]
Nice pull request ID

**Comment by Million900o** [comment]
I don't see why you have modify emoji code before modify channel or anything

**Comment by VoltrexMaster** [comment]
> I don't see why you have modify emoji code before modify channel or anything

I didn't make that method so i just formatted it, not changed its position

**Review by matthewthechickenman — APPROVED** [review]
Looking good!

**Pull request merged**
