### PR TITLE
Very important update, must fix now...

### PR DESCRIPTION
**Pull request by JLDENSMORE**
Very important update, must fix now...

### CODE REVIEW

**Review by matthewthechickenman — APPROVED** [review]
I mean, yea. It's a simple change that shouldn't really affect anything

**Comment by JLDENSMORE** [comment]
Yay, I snuck onto the contributors list without actually doing anything >:)

**Comment by matthewthechickenman** [comment]
did you?

**Comment by Misly16** [comment]
@JLDENSMORE as of npm 5, --save is no longer needed.

**Comment by JLDENSMORE** [comment]
> @JLDENSMORE as of npm 5, --save is no longer needed.

Hmm, good to know.

**Pull request merged**
