### PR TITLE
Emoji.ts improvements

### PR DESCRIPTION
**Pull request by null8626**
better than just showing `null` as URL for default discord emojis
also fixed this.animated operator bug maybe?

### CODE REVIEW

**Comment by matthewthechickenman** [comment]
checks failing :^)

**Comment by matthewthechickenman** [comment]
checks succeeding

**Comment by VoltrexMaster** [comment]
This PR would revert changes of https://github.com/ourcord/ourcord/pull/71, not a good idea

**Comment by matthewthechickenman** [comment]
> This PR would revert changes of #71, not a good idea

yOuRe JuSt sAyIng tHAt BEcAuse YoU mADe tHat pUl L rEqUeSt haha i'll fix the conflicts

**Comment by AndrewDaGuy** [comment]
checks failing

**Comment by matthewthechickenman** [comment]
> checks failing

fuck

**Comment by AndrewDaGuy** [comment]
when will the checks unfail

**Pull request closed without merging**
