### PR TITLE
Added ZLib support, changed how export work. 🔥✨✏️🔧♿️🍻🍻🍻🍻🍻🍻

### PR DESCRIPTION
**Pull request by Khaomi**

### CODE REVIEW

**Comment by AndrewDaGuy** [comment]
poggers

**Comment by xhayper** [comment]
this... is beautiful...
image

**Comment by Misly16** [comment]
@timotejroiko is the zlib implementation any similar to what you have?

**Comment by timotejroiko** [comment]
The flush flag should be Z_SYNC_FLUSH not Z_FULL_FLUSH, also this assumes the whole lib will only ever create a single websocket connection, aka no internal sharding support. This also doesnt correctly support disconnections and reconnections. Also no support for packet compression if one wants to use it instead of streams and idk about the performance of Buffer.compare (can test it later).

btw why do you guys have a flag parameter on ws? ws.on("message") does not emit a flag parameter according to the docs?

**Comment by alebot-dev** [comment]
# A professional note from the Ourcord developers

## Hello Tim <br />

Sick burn!

### \- The dev team

**Comment by timotejroiko** [comment]
lmao, this wasnt intended to be a burn, you did a good job trying to implement it, just needs a few pointers to the right direction

**Comment by xhayper** [comment]
Hello, Tim,

I fucked up

Sincerely, hayper.

**Comment by xhayper** [comment]
^^ tf
my ide do be formatting the code

**Comment by AndrewDaGuy** [comment]
how much f*cking conflicts are there

**Comment by xhayper** [comment]
yes

**Comment by matthewthechickenman** [comment]
hoLy FUCK that’s A LOT of conflicts

**Comment by alebot-dev** [comment]
Can you please resolve the conflicts? 
@xhayper

**Comment by xhayper** [comment]
why mE

**Comment by matthewthechickenman** [comment]
> why mE

do you want *me* to do it?

**Comment by xhayper** [comment]
yes

**Review by ghost — COMMENTED** [review]
your ide is having a seizure

**Review by ghost — CHANGES_REQUESTED** [review]
the list of things to fix (i think):

- Add formatting config files SO EVERY PR FUCKING DOE- 

- Revive these things:
    -  `package-lock.json`
    - `@types/chalk` and `@types/dotenv` in `package.json`

**Comment by xhayper** [comment]
damn a lot of conflict, too lazy to fix it doe

**Comment by AndrewDaGuy** [comment]
sOmEboDY fIX ThE FU*King COnfCLIcets

**Pull request closed without merging**
