### PR TITLE
Added .jshintrc, semicolons, eslint disable, and ourcord logo with some doc changes

### PR DESCRIPTION
**Pull request by AndrewDaGuy**
yes.

Changes:
- 🚚 Moved the ourcord logo to `assets/` instead of using discords
- 🔧Added `.jshintrc` 
- 🎨Semicolons ~~and those `eslint disable` things~~
- 📝`README.md`: Now uses `assets/logo.svg` for logo

### CODE REVIEW

**Comment by khalby786** [comment]
@AndrewDaGuy if you made changes to the README, please do the steps in the link so that the updated README shows up in the documentation: https://github.com/ourcord/ourcord/pull/53#issue-542950894

**Comment by AndrewDaGuy** [comment]
gimme a sec

**Comment by AndrewDaGuy** [comment]
this is good right?
image

**Comment by AndrewDaGuy** [comment]
either I fucked up something or it's supposed to do this
image

**Comment by khalby786** [comment]
Yes, you actually f**ked up lol. It's okay, I'll deploy a fix soon, nothing to worry about, it's actually my fault, so no worries.

**Comment by AndrewDaGuy** [comment]
ok i quit

**Comment by Misly16** [comment]
Hey, you disabled the squiggly bracket thing, but its from the stylesheet I would like to follow.

**Comment by Misly16** [comment]
Also if there's a eslint error I would prefer for the error to be fixed rather than a disable option

**Review by matthewthechickenman — APPROVED** [review]
We’re looking good for this one.

**Pull request merged**
